services:

  web:
    build: ../../apps/web
    ports:
      - "3000:3000"

  api:
    build: ../../apps/api
    ports:
      - "8000:8000"

  kali:
    build: ../../desktop-images/kali
    ports:
      - "8080:8080"
      - "5900:5900"