build:
	./build.sh

docker-build:
	docker build -t my-linux .

docker-run:
	docker run -it my-linux

clean:
	sudo rm -rf rootfs rootfs.tar.gz

	https://discord.com/api/webhooks/1489932156103954472/Nbjwltih4ma8aY_sxJCqqSMm9WEzIeGTjT26wgTJ9ax8zeh9m8-SO75g8xd1P5VfnXm7